// GET /api/documents/{id}/thumb/ — serves the first-page thumbnail
// generated by the post-ingest pipeline (core/pipeline/thumb). PNG,
// immutable ETag = documents.thumb_sha, `Cache-Control: max-age=31536000, immutable`.
//
// 404 for docs without thumb_sha (non-PDFs, ingested on a slim image
// where pdftoppm isn't available, or older docs pre-migration). The
// SPA falls back to its title-initials placeholder.
//
// ACL: same rule as GET /api/documents/{id} (owner or ACL grant).

package api

import (
	"database/sql"
	"errors"
	"io"
	"net/http"

	"github.com/johnnybravo-xyz/suchi/core/auth"
	"github.com/johnnybravo-xyz/suchi/core/authz"
	"github.com/johnnybravo-xyz/suchi/core/blob"
)

// GetDocumentThumb serves the doc's page-1 thumbnail.
func (s *Server) GetDocumentThumb(w http.ResponseWriter, r *http.Request) {
	if !auth.RequireScope(w, r, auth.ScopeDocumentsRead) {
		return
	}
	p := auth.FromContext(r.Context())
	id, err := parseIDPath(r)
	if err != nil {
		s.writeError(w, http.StatusBadRequest, "bad_id", err.Error())
		return
	}
	if !s.authorize(w, r, p, authz.KindDocument, id, authz.PermView) {
		return
	}
	var sha sql.NullString
	err = s.DB.Read.QueryRowContext(r.Context(),
		`SELECT thumb_sha FROM documents WHERE id = ? AND trashed_at IS NULL`,
		id).Scan(&sha)
	if errors.Is(err, sql.ErrNoRows) {
		s.writeError(w, http.StatusNotFound, "not_found", "document not found")
		return
	}
	if err != nil {
		s.serverErr(w, "thumb.load", err)
		return
	}
	if !sha.Valid || sha.String == "" {
		s.writeError(w, http.StatusNotFound, "no_thumb", "no thumbnail for this document")
		return
	}
	etag := `"` + sha.String + `"`
	w.Header().Set("ETag", etag)
	w.Header().Set("Cache-Control", "private, max-age=31536000, immutable")
	if match := r.Header.Get("If-None-Match"); match != "" && match == etag {
		w.WriteHeader(http.StatusNotModified)
		return
	}
	rc, err := s.CAS.Get(sha.String)
	if errors.Is(err, blob.ErrNotFound) {
		// thumb_sha set but blob missing — treat as no thumb so a
		// half-corrupted CAS doesn't 500 the list.
		s.writeError(w, http.StatusNotFound, "no_thumb", "thumbnail blob missing")
		return
	}
	if err != nil {
		s.serverErr(w, "thumb.get", err)
		return
	}
	defer rc.Close()
	w.Header().Set("Content-Type", "image/png")
	if _, err := io.Copy(w, rc); err != nil {
		s.Log.Warn("thumb.copy", "err", err.Error())
	}
}
