// SPDX-License-Identifier: AGPL-3.0-or-later

// Package index projects the current tree-only taxonomy snapshot into a managed
// HuML file. The durable job contains no captured tree and never creates documents.
package index

import (
	"bytes"
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"os"
	"sync"

	"github.com/johnnybravo-xyz/suchi/core/db"
	"github.com/johnnybravo-xyz/suchi/core/jd/presetfile"
	"github.com/johnnybravo-xyz/suchi/core/jd/systems"
	"github.com/johnnybravo-xyz/suchi/core/jobs"
	"github.com/johnnybravo-xyz/suchi/core/render/paths"
	"github.com/johnnybravo-xyz/suchi/core/taxonomy/exporter"
	pluginapi "github.com/johnnybravo-xyz/suchi/plugin-api"
)

const Kind = "taxonomy_index"
const Filename = "00.00 archive.huml"
const generatedHeader = "# Generated by Suchi: filing index. Do not edit this managed file.\n# System areas are implicit; keywords and automations are intentionally excluded.\n"

func Enqueue(ctx context.Context, tx *sql.Tx, systemID int64) error {
	if systemID <= 0 {
		return fmt.Errorf("taxonomy index requires a system")
	}
	payload, err := json.Marshal(struct {
		SystemID int64 `json:"system_id"`
	}{systemID})
	if err != nil {
		return err
	}
	return jobs.Enqueue(ctx, tx, Kind, 0, systemID, string(payload))
}

// Handler serializes snapshots and writes so an older concurrent request cannot
// replace a newer one. Every invocation exports current committed database state.
type Handler struct {
	db         *db.DB
	log        *slog.Logger
	renderRoot string
	mu         sync.Mutex
	// Instance-local publication barrier for deterministic transition tests.
	beforePublish func()
}

func New(d *db.DB, log *slog.Logger, renderRoot string) *Handler {
	return &Handler{db: d, log: log.With("component", Kind), renderRoot: renderRoot}
}
func (h *Handler) Kinds() []string { return []string{Kind} }
func (h *Handler) Handle(ctx context.Context, event pluginapi.Event) error {
	raw, _ := event.Payload["raw"].(string)
	var payload struct {
		SystemID int64 `json:"system_id"`
	}
	if err := json.Unmarshal([]byte(raw), &payload); err != nil {
		return fmt.Errorf("taxonomy index payload: %w", err)
	}
	systemID := payload.SystemID
	if systemID <= 0 || event.SystemID != systemID {
		return fmt.Errorf("taxonomy index payload does not match job system")
	}
	h.mu.Lock()
	defer h.mu.Unlock()
	pf, err := exporter.BuildExport(ctx, h.db, systemID, true)
	if err == nil {
		var data []byte
		data, err = presetfile.Marshal(pf, presetfile.FormatHuML)
		if err == nil {
			// A HuML directive must be the first line. The index has an
			// ownership comment instead; the optional directive is omitted.
			if bytes.HasPrefix(data, []byte("%HUML ")) {
				_, data, _ = bytes.Cut(data, []byte("\n"))
			}
			if h.beforePublish != nil {
				h.beforePublish()
			}
			err = writeIndex(ctx, h.renderRoot, pf.System, append([]byte(generatedHeader), data...))
			if err == nil && systemID == systems.DefaultID && pf.System != "" {
				err = removeLegacyIndex(h.renderRoot)
			}
		}
	}
	if err != nil {
		h.log.Error("taxonomy.index.refresh_failed", "err", err)
		return fmt.Errorf("taxonomy index: %w", err)
	}
	h.log.Info("taxonomy.index.refreshed", "system_id", systemID, "system", pf.System, "path", paths.IndexDirectory+"/"+Filename)
	return nil
}

func writeIndex(ctx context.Context, renderRoot, systemCode string, data []byte) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	// The configured root already exists (the document renderer owns it).
	info, err := os.Lstat(renderRoot)
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("render root must be a real directory, not a symlink")
	}
	root, err := os.OpenRoot(renderRoot)
	if err != nil {
		return err
	}
	defer root.Close()
	opened, err := root.Stat(".")
	if err != nil {
		return err
	}
	if !os.SameFile(info, opened) {
		return fmt.Errorf("render root changed while opening")
	}
	if systemCode != "" {
		if !systems.ValidCode(systemCode) {
			return fmt.Errorf("invalid system index code")
		}
		systemRoot, err := openDirectory(root, systemCode, true)
		if err != nil {
			return err
		}
		defer systemRoot.Close()
		root = systemRoot
	}
	if err := root.Mkdir(paths.IndexDirectory, 0o750); err != nil && !errors.Is(err, os.ErrExist) {
		return err
	}
	info, err = root.Lstat(paths.IndexDirectory)
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("index parent must be a real directory, not a symlink")
	}
	dir, err := root.OpenRoot(paths.IndexDirectory)
	if err != nil {
		return err
	}
	defer dir.Close()
	opened, err = dir.Stat(".")
	if err != nil {
		return err
	}
	if !os.SameFile(info, opened) {
		return fmt.Errorf("index parent changed while opening")
	}
	if err := checkManagedTarget(dir); err != nil {
		return err
	}
	temp := ".taxonomy-index-" + rand.Text() + ".tmp"
	f, err := dir.OpenFile(temp, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o640)
	if err != nil {
		return err
	}
	defer dir.Remove(temp)
	if _, err := f.Write(data); err != nil {
		f.Close()
		return err
	}
	if err := f.Sync(); err != nil {
		f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	if err := checkManagedTarget(dir); err != nil {
		return err
	}
	if err := dir.Rename(temp, Filename); err != nil {
		return err
	}
	// Persist the directory entry as well as the completed file contents.
	parent, err := dir.Open(".")
	if err != nil {
		return err
	}
	defer parent.Close()
	return parent.Sync()
}

func checkManagedTarget(dir *os.Root) error {
	info, err := dir.Lstat(Filename)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("refusing non-regular index target %s", Filename)
	}
	f, err := dir.Open(Filename)
	if err != nil {
		return err
	}
	defer f.Close()
	opened, err := f.Stat()
	if err != nil {
		return err
	}
	if !os.SameFile(info, opened) {
		return fmt.Errorf("index target changed while opening")
	}
	header := make([]byte, len(generatedHeader))
	if _, err := io.ReadFull(f, header); err != nil || !bytes.Equal(header, []byte(generatedHeader)) {
		return fmt.Errorf("refusing unexpected user file at %s; move it before refreshing the generated index", Filename)
	}
	return nil
}

// openDirectory pins a real child directory and rejects symlink parents.
func openDirectory(root *os.Root, name string, create bool) (*os.Root, error) {
	if create {
		if err := root.Mkdir(name, 0o750); err != nil && !errors.Is(err, os.ErrExist) {
			return nil, err
		}
	}
	info, err := root.Lstat(name)
	if err != nil {
		return nil, err
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("index parent must be a real directory")
	}
	dir, err := root.OpenRoot(name)
	if err != nil {
		return nil, err
	}
	opened, err := dir.Stat(".")
	if err != nil || !os.SameFile(info, opened) {
		dir.Close()
		if err != nil {
			return nil, err
		}
		return nil, fmt.Errorf("index parent changed while opening")
	}
	return dir, nil
}

// Only the original system calls this, after publishing its named index.
// Unknown files and directories remain untouched, including non-index siblings.
func removeLegacyIndex(renderRoot string) error {
	info, err := os.Lstat(renderRoot)
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("render root must be a real directory")
	}
	root, err := os.OpenRoot(renderRoot)
	if err != nil {
		return err
	}
	defer root.Close()
	opened, err := root.Stat(".")
	if err != nil {
		return err
	}
	if !os.SameFile(info, opened) {
		return fmt.Errorf("render root changed while opening")
	}
	legacyParent, err := root.Lstat(paths.IndexDirectory)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if !legacyParent.IsDir() {
		return nil
	}
	dir, err := openDirectory(root, paths.IndexDirectory, false)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	defer dir.Close()
	info, err = dir.Lstat(Filename)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if !info.Mode().IsRegular() {
		return nil
	}
	if err := checkManagedTarget(dir); err != nil {
		return nil
	}
	current, err := dir.Lstat(Filename)
	if err != nil {
		return err
	}
	if !os.SameFile(info, current) {
		return fmt.Errorf("legacy index changed before cleanup")
	}
	if err := dir.Remove(Filename); err != nil {
		return err
	}
	parent, err := dir.Open(".")
	if err != nil {
		return err
	}
	defer parent.Close()
	return parent.Sync()
}
