package presetfile

import (
	"fmt"
	"reflect"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/johnnybravo-xyz/suchi/core/automations"
	"github.com/johnnybravo-xyz/suchi/core/jd/systems"
)

// Validate accepts only raw author-owned structure, not generated runtime rows.
func Validate(pf *PresetFile) Errors {
	if pf == nil {
		return Errors{noPos("nil PresetFile")}
	}
	if pf.Format != Format {
		return Errors{noPos("format must be %q, got %q", Format, pf.Format)}
	}
	var es Errors
	add := func(format string, args ...any) { es = append(es, noPos(format, args...)) }
	if pf.System != "" && !systems.ValidCode(pf.System) {
		add("system: must match [A-Z][0-9]{2}")
	}
	text := func(path, value string, max int, required bool) {
		if required && strings.TrimSpace(value) == "" {
			add("%s: required", path)
		}
		if max > 0 && utf8.RuneCountInString(value) > max {
			add("%s: too long (maximum %d characters)", path, max)
		}
	}
	if !validID(pf.ID) {
		add("id: must match [a-z0-9][a-z0-9_-]*")
	}
	if pf.Version <= 0 {
		add("version: must be a positive integer")
	}
	text("name", pf.Name, 80, true)
	text("story", pf.Story, 500, true)
	text("market", pf.Market, 0, true)
	text("language", pf.Language, 0, true)
	if pf.Inbox != 0 {
		add("inbox: generated by Suchi; remove the author declaration")
	}
	areas := pf.Areas
	if pf.Flat {
		if pf.Areas != nil {
			add("areas: forbidden when flat is true")
		}
		if len(pf.Categories) < 1 || len(pf.Categories) > 9 {
			add("categories: flat input requires 1–9 categories")
		}
		cats := append([]Category(nil), pf.Categories...)
		for i := range cats {
			if cats[i].Code != 0 && cats[i].Code != 11+i {
				add("categories[%d].code: must be %d", i, 11+i)
			}
			cats[i].Code = 11 + i
		}
		areas = []Area{{Code: 10, Name: pf.Name, Categories: cats}}
	} else {
		if pf.Areas == nil {
			add("areas: explicit collection required (use an empty list for a blank tree)")
		}
		if pf.Categories != nil {
			add("categories: forbidden unless flat is true")
		}
	}
	if len(areas) > 8 {
		add("areas: too many areas (maximum 8)")
	}
	seenAreas, seenCats := map[int]bool{}, map[int]bool{}
	for i, a := range areas {
		p := fmt.Sprintf("areas[%d]", i)
		if a.Code < 10 || a.Code > 90 || a.Code%10 != 0 || a.Code == 40 {
			add("%s.code: must be a user decade start (10, 20, 30, 50, 60, 70, 80, 90)", p)
		}
		if seenAreas[a.Code] {
			add("%s.code: duplicate code %d", p, a.Code)
		}
		seenAreas[a.Code] = true
		text(p+".name", a.Name, 80, true)
		if a.Categories == nil {
			add("%s.categories: explicit collection required", p)
		}
		for j, c := range a.Categories {
			cp := fmt.Sprintf("%s.categories[%d]", p, j)
			if c.Code <= a.Code || c.Code > a.Code+9 || c.Code < 11 || c.Code/10 == 4 {
				add("%s.code: %d outside area %d-%d or reserved", cp, c.Code, a.Code, a.Code+9)
			}
			if seenCats[c.Code] {
				add("%s.code: duplicate code %d", cp, c.Code)
			}
			seenCats[c.Code] = true
			text(cp+".name", c.Name, 80, true)
			text(cp+".description", c.Description, 240, false)
			if len(c.Keywords) > 20 {
				add("%s.keywords: at most 20 keywords", cp)
			}
			for k, kw := range c.Keywords {
				text(fmt.Sprintf("%s.keywords[%d]", cp, k), kw, 40, true)
			}
		}
	}
	if pf.Seeds != nil {
		names := map[string]bool{}
		for i, a := range pf.Seeds.Automations {
			p := fmt.Sprintf("seeds.automations[%d]", i)
			text(p+".name", a.Name, 80, true)
			if names[a.Name] {
				add("%s.name: duplicate starter name %q", p, a.Name)
			}
			names[a.Name] = true
			t := a.Trigger
			if err := automations.ValidateTriggers([]automations.Trigger{{TypeCode: t.Type, FilterPath: t.FilterPath, FilterFilename: t.FilterFilename, FilterTitleRE: t.FilterTitleMatching, FilterContentRE: t.FilterContentMatching, FilterEmailFrom: t.FilterEmailFrom, FilterEmailSubject: t.FilterEmailSubject, FilterEmailFolder: t.FilterEmailFolder, FilterEmailHasAttachment: t.FilterEmailHasAttachment}}); err != nil {
				add("%s.trigger: %v", p, err)
			}
			if len(a.Actions) == 0 {
				add("%s.actions: at least one action required", p)
			}
			for j, act := range a.Actions {
				if err := validateAction(act, seenCats); err != nil {
					add("%s.actions[%d]: %v", p, j, err)
				}
			}
		}
	}
	return es
}

func validateAction(a Action, cats map[int]bool) error {
	key := ""
	switch a.Kind {
	case "assign_title":
		key = "template"
	case "assign_correspondent":
		key = "correspondent"
	case "assign_document_type":
		key = "document_type"
	case "assign_jd_category":
		key = "jd_category_code"
	case "assign_tags":
		_, tag := a.Params["tag"]
		_, tags := a.Params["tags"]
		if tag == tags {
			return fmt.Errorf("params: provide exactly one of tag or tags")
		}
		key = "tag"
		if tags {
			key = "tags"
		}
	default:
		return fmt.Errorf("kind: unsupported portable action %q", a.Kind)
	}
	keys := make([]string, 0, len(a.Params))
	for k := range a.Params {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		if k != key {
			return fmt.Errorf("params.%s: unsupported parameter for %s", k, a.Kind)
		}
	}
	value, ok := a.Params[key]
	if !ok {
		return fmt.Errorf("params.%s: required", key)
	}
	switch key {
	case "jd_category_code":
		var code int
		switch v := value.(type) {
		case int:
			code = v
		case int64:
			code = int(v)
			if int64(code) != v {
				return fmt.Errorf("params.%s: integer out of range", key)
			}
		default:
			return fmt.Errorf("params.%s: expected integer", key)
		}
		if !cats[code] || code < 11 || code/10 == 4 || code%10 == 0 {
			return fmt.Errorf("params.%s: must reference a declared user category, got %d", key, code)
		}
	case "tags":
		v := reflect.ValueOf(value)
		if !v.IsValid() || v.Kind() != reflect.Slice || v.Len() == 0 {
			return fmt.Errorf("params.tags: nonempty string list required")
		}
		for i := range v.Len() {
			s, ok := v.Index(i).Interface().(string)
			if !ok || strings.TrimSpace(s) == "" {
				return fmt.Errorf("params.tags[%d]: nonempty string required", i)
			}
		}
	default:
		s, ok := value.(string)
		if !ok || strings.TrimSpace(s) == "" {
			return fmt.Errorf("params.%s: nonempty string required", key)
		}
	}
	return nil
}

// ValidateNormalized protects importer entry points that receive an in-memory tree.
func ValidateNormalized(pf *PresetFile) error {
	_, err := rawFromNormalized(pf)
	return err
}

func rawFromNormalized(pf *PresetFile) (*PresetFile, error) {
	if pf == nil {
		return nil, Errors{noPos("nil PresetFile")}
	}
	if pf.Inbox != 49 || pf.Categories != nil {
		return nil, Errors{noPos("normalized tree requires generated Inbox 49 and no raw categories")}
	}
	raw := *pf
	raw.Inbox = 0
	raw.Areas = make([]Area, 0, len(pf.Areas))
	systems := 0
	for _, a := range pf.Areas {
		if a.Code != 40 {
			raw.Areas = append(raw.Areas, a)
			continue
		}
		systems++
		if a.Name != "System" || len(a.Categories) != 1 || a.Categories[0].Code != 49 || a.Categories[0].Name != "Inbox" || a.Categories[0].Description != "" || len(a.Categories[0].Keywords) != 0 {
			return nil, Errors{noPos("reserved area 40 must contain only generated System / 49 Inbox; legacy/custom reserved content cannot be exported or imported")}
		}
	}
	if systems != 1 {
		return nil, Errors{noPos("normalized tree requires exactly one generated 40 System / 49 Inbox")}
	}
	if raw.Flat {
		if len(raw.Areas) != 1 || raw.Areas[0].Code != 10 || raw.Areas[0].Name != raw.Name {
			return nil, Errors{noPos("normalized flat tree requires area 10 named after the taxonomy")}
		}
		raw.Categories = raw.Areas[0].Categories
		raw.Areas = nil
	}
	if es := Validate(&raw); len(es) != 0 {
		return nil, es
	}
	return &raw, nil
}

func validID(id string) bool {
	if id == "" {
		return false
	}
	for i, r := range id {
		if r >= 'a' && r <= 'z' || r >= '0' && r <= '9' || i > 0 && (r == '-' || r == '_') {
			continue
		}
		return false
	}
	return true
}
