package pageanalyze

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

// writePGM writes a synthetic P5 (binary, 8-bit) PGM. Every pixel
// takes the same value — good enough for whiteness-mean tests.
func writePGM(t *testing.T, path string, width, height, value int) {
	t.Helper()
	if value < 0 || value > 255 {
		t.Fatalf("bad value %d", value)
	}
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "P5\n%d %d\n255\n", width, height)
	pix := bytes.Repeat([]byte{byte(value)}, width*height)
	buf.Write(pix)
	if err := os.WriteFile(path, buf.Bytes(), 0o600); err != nil {
		t.Fatal(err)
	}
}

func TestMeanWhitePGM_AllWhite(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "white.pgm")
	writePGM(t, p, 10, 10, 255)
	m, err := meanWhitePGM(p)
	if err != nil {
		t.Fatal(err)
	}
	if m != 1.0 {
		t.Errorf("all-white PGM should be 1.0, got %v", m)
	}
}

func TestMeanWhitePGM_AllBlack(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "black.pgm")
	writePGM(t, p, 10, 10, 0)
	m, err := meanWhitePGM(p)
	if err != nil {
		t.Fatal(err)
	}
	if m != 0.0 {
		t.Errorf("all-black PGM should be 0.0, got %v", m)
	}
}

func TestMeanWhitePGM_Mid(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "mid.pgm")
	writePGM(t, p, 20, 20, 128)
	m, err := meanWhitePGM(p)
	if err != nil {
		t.Fatal(err)
	}
	want := 128.0 / 255.0
	if diff := m - want; diff > 0.001 || diff < -0.001 {
		t.Errorf("got %v want ~%v", m, want)
	}
}

func TestMeanWhitePGM_WithComments(t *testing.T) {
	// PGM comments are legal between header tokens; make sure we skip them.
	dir := t.TempDir()
	p := filepath.Join(dir, "commented.pgm")
	var buf bytes.Buffer
	buf.WriteString("P5\n")
	buf.WriteString("# generated by test\n")
	buf.WriteString("4 2\n")
	buf.WriteString("# maxval below\n")
	buf.WriteString("255\n")
	buf.Write(bytes.Repeat([]byte{200}, 8))
	if err := os.WriteFile(p, buf.Bytes(), 0o600); err != nil {
		t.Fatal(err)
	}
	m, err := meanWhitePGM(p)
	if err != nil {
		t.Fatal(err)
	}
	want := 200.0 / 255.0
	if diff := m - want; diff > 0.001 || diff < -0.001 {
		t.Errorf("commented PGM: got %v want ~%v", m, want)
	}
}

func TestListPGMs_NumericOrder(t *testing.T) {
	dir := t.TempDir()
	for _, name := range []string{"p-10.pgm", "p-2.pgm", "p-1.pgm", "unrelated.txt"} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte("x"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	got, err := listPGMs(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := []int{1, 2, 10}
	if len(got) != len(want) {
		t.Fatalf("got %v want len %d", got, len(want))
	}
	for i, g := range got {
		if g.n != want[i] {
			t.Errorf("[%d] got %d want %d", i, g.n, want[i])
		}
	}
}
